### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by eshoule** [cjthom03/UdemyClone#1]
## MVPs
- [x] Put new account creation/login before hosting on Heroku so that you have something to host.
- [x] Add estimations for how long each MVP will take.
- [x] Add bullet points providing details for each MVP (e.g. Users can sign up, sign in, logout / Users can use a demo login to try the site / Users can't use certain features without logging out).
- [x] Add the following bullet points to each MVP 
  * Adequate styling
  * Smooth, bug-free navigation
  * Seeded with info to demonstrate this feature
---

## Schema
- [x] Add bullet points after the table that state which foreign keys will reference to which table, or references to the associations that will be made.
- [x] Format table names and column names to be ```back-ticked```.
- Comment: If you're doing your search based on course title and/or author, you shouldn't need additional data fields. 
---

## Routes
- [x] Add an HTML route
- Answer to your questions: Yes, I think POST requests to your subscriptions and completions are good methods to create those entries/update the tables. It seems the tricky part is determining when your course is complete/when to make that request.
---

## Sample State
- [x] Normalize your state shape to reflect this documentation/standard https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#relationships-and-tables. The bluebird example is good to follow when normalizing the state shape (https://github.com/appacademy/bluebird/). You shouldn't need an array of lesson ids and instead you will have a selector.
---

## Component Hierarchy
- [x] Ensure all routes listed in the routes wiki page is also listed in the component hierarchy.
- [x] If necessary, each component should have route, state, and other components it renders. Use this for guidance (https://github.com/appacademy/bluebird/wiki/component-hierarchy).

**Comment by cjthom03** [comment]
Liz - Thank you for your feedback. I have updated the docs for each of the above items and I have noted below any special or additional changes. 

Please note:
* I removed `/login` and `/signup` front-end routes. In order to mimic Udemy, I will use login/signup form modals that appear when the user explicitly clicks on the login/signup buttons or tries to interact with the site in way that requires login. Containers will be conditionally rendered, but front end routes will not be needed.
* Sample State: I added a slice of state for `subscriptions` but decided to organize the data by `course_id` instead of `subscription_id`. This is because we only care about the subscriptions for the current user and they will be looked up by the `course_id`. Organizing it this way should allow me to access a given subscription in O(1) time and I can use a selector if I need a collection of subscriptions.
* Sample State: See comment above, but for the `completions` slice of state that I added. `completions` are organized by `lesson_id` instead of `completion_id`

**Comment by eshoule** [comment]
Everything looks great, Charlie!
